//
//  profileData.swift
//  MediaMine
//
//  Created by Christopher Chu on 7/27/19.
//  Copyright © 2019 Christopher Chu. All rights reserved.
//

import Foundation
import UIKit


var temp = [String]()
let userProfileData = UserDefaults.standard

var stocks = ["WMT",
              "GM",
              "GE",
              "CVX",
              "PM",
              "AIG",
              "AEP",
              "BA",
              "HD",
              "JPM",
              "CAH",
              "MRK",
              "HPE",
              "MCK",
              "JNJ",
              "COP",
              "PFE",
              "JCP",
              "MET",
              "GS",
              "MSI",
              "ALL",
              "UTX",
              "DOW",
              "CAG",
              "PEP",
              "WFC",
              "INTC",
              "DLPH",
              "S",
              "DD",
              "DIS",
              "LMT",
              "PSX",
              "HON",
              "UNH",
              "VIA",
              "AXP",
              "CSCO",
              "CVS",
              "LOW",
              "BMY",
              "AN",
              "CTL",
              "CI",
              "ORCL",
              "HCA",
              "RTN",
              "XRX",
              "ABT",
              "HIG",
              "MCD",
              "GT",
              "GPS",
              "NOC",
              "HAL",
              "DE",
              "KODK",
              "SUN",
              "TXT",
              "EIX",
              "UNP",
              "WM",
              "ODP",
              "WHR",
              "HUM",
              "SO",
              "MAR",
              "CMCSA",
              "AFL",
              "KHC",
              "CL",
              "BURL",
              "A",
              "ASH",
              "DDS",
              "TXN",
              "CCO",
              "DTE",
              "KSS",
              "PGR",
              "GIS",
              "PNC",
              "AVYA",
              "FITB",
              "R",
              "BKS",
              "AZO",
              "LEVI",
              "MGM",
              "STWD",
              "CLX",
              "BLL",
              "BIG",
              "HRB",
              "SBUX",
              "WEN",
              "LZB",
              "CTAS",
              "ALK",
              "DLTR",
              "CBRL",
              "JACK",
              "SMG",
              "LE",
              "FDP",
              "PIR",
              "AEO",
              "NVDA",
              "ANF",
              "REV",
              "SMRT",
              "BOH",
              "INTU",
              "CNXN",
              "AAPL",
              "FB",
              "GOOG",
              "AMZN",
              "TWTR"
]
